### ISSUE TITLE
Missing AndroidNetworkCallback Class – Found FakeAndroidNetworkCallback Instead

### ISSUE THREAD

**Issue by ChaaruManjurajKomala** [OpenDDS/OpenDDS#4814]
I'm encountering a ClassNotFoundException while running my Android project that uses OpenDDS. The issue comes when the project attempts to reference the class OpenDDS.DCPS.AndroidNetworkCallback, which seems to be missing.

Here’s the relevant excerpt from the log:

```
java.lang.ClassNotFoundException: Didn't find class "OpenDDS.DCPS.AndroidNetworkCallback" on path: DexPathList[[zip file "/data/app/~~aWFwdQizKKY1AnoqwyElRQ==/com.example.sdv_security_manager-F9ZQt7JTQz4VFn3nor-ccg==/base.apk"],nativeLibraryDirectories=[/data/app/~~aWFwdQizKKY1AnoqwyElRQ==/com.example.sdv_security_manager-F9ZQt7JTQz4VFn3nor-ccg==/lib/arm64, /data/app/~~aWFwdQizKKY1AnoqwyElRQ==/com.example.sdv_security_manager-F9ZQt7JTQz4VFn3nor-ccg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
    at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at DDS.DomainParticipantFactory OpenDDS.DCPS.TheParticipantFactory.WithArgs(org.omg.CORBA.StringSeqHolder) (TheParticipantFactory.java:-2)
    at void com.example.sdv_security_manager.MainActivity.startDDSSubscriber(MainActivity.java:61)
    at void com.example.sdv_security_manager.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:50)
```

What I Found
Upon inspecting the OpenDDS_DCPS.jar file, I found `OpenDDS/DCPS/FakeAndroidNetworkCallback.class` instead of `AndroidNetworkCallback`:

It appears that FakeAndroidNetworkCallback is present in the JAR, but AndroidNetworkCallback is missing. 

I've included the following `.jar` files in `app/lib`:
i2jrt_corba.jar
i2jrt.jar
OpenDDS_DCPS.jar
tao_java.jar

**Comment by iguessthislldo** [comment]
I was able to recreate the issue. If you're still using OpenDDS-Android like you mentioned in the other issue, it looks like I failed to update the scripts properly after https://github.com/OpenDDS/OpenDDS/pull/2237.

OpenDDS-Android sets [`ANDROID_SDK`](https://github.com/OpenDDS/OpenDDS-Android/blob/cd06b8baf98edcc090a73ee06adcb5b3a1ae3051/setenv.sh#L157) and [`target_api`](https://github.com/OpenDDS/OpenDDS-Android/blob/cd06b8baf98edcc090a73ee06adcb5b3a1ae3051/default.settings.sh#L13) when it should be setting [`android_sdk`](https://opendds.readthedocs.io/en/master/devguide/building/android.html#android-sdk) and [`android_target_api`](https://opendds.readthedocs.io/en/master/devguide/building/android.html#android-target-api).

Could you try this:
1.  `rm OpenDDS/build/target/lib/OpenDDS_DCPS.jar`
2. Add this to the bottom of `setenv.sh`:

  ```
  export android_sdk="$ANDROID_SDK"
  export android_target_api="$target_api"
  ```
  
3. Try `./build.sh` again.

I did something similar to this and I now have a `OpenDDS_DCPS.jar` with `AndroidNetworkCallback.class` in it.

I will change OpenDDS-Android shortly to fix this.
