### ISSUE TITLE
Segmentation fault in binary compiled with catkin_make (ROS) instead of make. (create_datawriter function)

### ISSUE THREAD

**Issue by vidalperezbohoyo** [OpenDDS/OpenDDS#4868]
**Computer:**
- Ubuntu 20.04
- OpenDDS 3.30
- ROS Noetic

**What i want to do**
I want to create a OpenDDS publisher inside a ROS1 node to publish via DDS one type of message received from ROS.

**The code used to test the concept**
I created a simple main.cpp with the code from Messenger example (Messenger.idl and default QOS). Without any class or ROS code. (I have tested with ros init and so and is the same problem). 

**The problem**
I noticed, with several time spend on it, that if i compile the same code with catkin_make and make, the result is not the same.
With catkin_make all works fine until reaches the function "create_datawriter" from OpenDDS. Then several error crashes. Segmentation faults, invalid pointer, bus error etc. Every time i run it, the error is different. 
With the binary compiled with make it is okay. No crashes.

**What i tried to fix it(without success)**
- Use the Messenger example code and idl
- Use a CMake very similar to the Messenger Example
- Compile catkin_make with -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-O0 options (Internet says that remove optimizations)
- Use gdb to see where is the fault. Every time i run it, the backtrace is different. Always crashing inside the create_datawriter call
- Call the program with the full path to the binary instead of using rosrun
- Using the rtps.ini
- Test FastDDS inside of this node, works fine with no crashes.

**One of the crashes GDB output (In this case is free(): invalid pointer)**
```
Thread 1 "mobile_inte" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff4e25859 in __GI_abort () at abort.c:79
#2  0x00007ffff4e9026e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff4fba298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff4e982fc in malloc_printerr (str=str@entry=0x7ffff4fb84c1 "free(): invalid pointer") at malloc.c:5347
#4  0x00007ffff4e99b2c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x00007ffff53183a5 in ACE_New_Allocator::free (this=0x7ffff540de98 <ACE_Allocator::instance()::allocator_instance>, ptr=0x7ffff5f56d5d <OpenDDS::DCPS::DataWriterImpl::enable()+2929>)
    at /home/user/Downloads/OpenDDS-3.30/ACE_wrappers/ace/Malloc_Allocator.cpp:127
#6  0x00007ffff5e4fe2d in OpenDDS::DCPS::PoolAllocationBase::operator delete (ptr=0x7ffff5f56d5d <OpenDDS::DCPS::DataWriterImpl::enable()+2929>) at ../dds/DCPS/PoolAllocationBase.h:63
#7  0x00007ffff61effcc in std::default_delete<OpenDDS::XTypes::TypeIdentifier>::operator() (this=0x7fffffffcaa8, __ptr=0x7ffff5f56d5d <OpenDDS::DCPS::DataWriterImpl::enable()+2929>)
    at /usr/include/c++/9/bits/unique_ptr.h:81
#8  0x00007ffff620fc62 in std::unique_ptr<OpenDDS::XTypes::TypeIdentifier, std::default_delete<OpenDDS::XTypes::TypeIdentifier> >::~unique_ptr (this=0x7fffffffcaa8, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/unique_ptr.h:292
#9  0x00007ffff620eecc in OpenDDS::XTypes::External<OpenDDS::XTypes::TypeIdentifier>::~External (this=0x7fffffffcaa8, __in_chrg=<optimized out>)
    at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/XTypes/External.h:26
#10 0x00007ffff620fb72 in OpenDDS::XTypes::PlainMapSTypeDefn::~PlainMapSTypeDefn (this=0x7fffffffcaa0, __in_chrg=<optimized out>) at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/XTypes/TypeObject.h:477
#11 0x00007ffff61fe422 in OpenDDS::XTypes::TypeIdentifier::reset (this=0x7fffffffca68) at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/XTypes/TypeObject.cpp:157
#12 0x00007ffff5e506fe in OpenDDS::XTypes::TypeIdentifier::~TypeIdentifier (this=0x7fffffffca68, __in_chrg=<optimized out>) at ../dds/DCPS/XTypes/TypeObject.h:655
#13 0x00007ffff5e51266 in OpenDDS::XTypes::CommonStructMember::~CommonStructMember (this=0x7fffffffca60, __in_chrg=<optimized out>) at ../dds/DCPS/XTypes/TypeObject.h:1140
#14 0x00007ffff5e60b84 in OpenDDS::XTypes::MinimalStructMember::~MinimalStructMember (this=0x7fffffffca60, __in_chrg=<optimized out>) at ../dds/DCPS/XTypes/TypeObject.h:1260
#15 0x00007ffff5e60ba3 in std::_Destroy<OpenDDS::XTypes::MinimalStructMember> (__pointer=0x7fffffffca60) at /usr/include/c++/9/bits/stl_construct.h:98
#16 0x00007ffff5e5f373 in std::_Destroy_aux<false>::__destroy<OpenDDS::XTypes::MinimalStructMember*> (__first=0x7fffffffca60, __last=0x0) at /usr/include/c++/9/bits/stl_construct.h:108
#17 0x00007ffff5e5cbde in std::_Destroy<OpenDDS::XTypes::MinimalStructMember*> (__first=0x7fffffffc790, __last=0x0) at /usr/include/c++/9/bits/stl_construct.h:137
#18 0x00007ffff5e5a243 in std::_Destroy<OpenDDS::XTypes::MinimalStructMember*, OpenDDS::XTypes::MinimalStructMember> (__first=0x7fffffffc790, __last=0x0) at /usr/include/c++/9/bits/stl_construct.h:206
#19 0x00007ffff60e5a2c in std::vector<OpenDDS::XTypes::MinimalStructMember, std::allocator<OpenDDS::XTypes::MinimalStructMember> >::_M_erase_at_end (this=0x7fffffffc618, __pos=0x7fffffffc790)
    at /usr/include/c++/9/bits/stl_vector.h:1793
#20 0x00007ffff61f1ae6 in std::vector<OpenDDS::XTypes::MinimalStructMember, std::allocator<OpenDDS::XTypes::MinimalStructMember> >::resize (this=0x7fffffffc618, __new_size=5)
    at /usr/include/c++/9/bits/stl_vector.h:939
#21 0x00007ffff61ef4af in OpenDDS::XTypes::Sequence<OpenDDS::XTypes::MinimalStructMember>::length (this=0x7fffffffc618, len=5) at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/XTypes/TypeObject.h:92
#22 0x00007ffff621101b in OpenDDS::DCPS::operator>><OpenDDS::XTypes::MinimalStructMember> (strm=..., seq=...) at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/XTypes/TypeObject.h:3538
#23 0x00007ffff6202676 in OpenDDS::DCPS::operator>> (strm=..., stru=...) at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/XTypes/TypeObject.cpp:1756
#24 0x00007ffff620d64b in OpenDDS::DCPS::operator>> (ser=..., type_object=...) at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/XTypes/TypeObject.cpp:4787
#25 0x00007ffff620d9d2 in OpenDDS::DCPS::operator>> (ser=..., type_object=...) at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/XTypes/TypeObject.cpp:4862
#26 0x00007ffff620e226 in OpenDDS::DCPS::to_type_object (
    buffer=0x555555db48c0 <OpenDDS::DCPS::(anonymous namespace)::opendds_idl_generated_messengertypesupportimpl_cpp_apfngh_minimal_to0()::to_bytes> "c", size=103, to=...)
    at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/XTypes/TypeObject.cpp:5059
#27 0x0000555555d6bee8 in OpenDDS::DCPS::(anonymous namespace)::opendds_idl_generated_messengertypesupportimpl_cpp_apfngh_minimal_to0 ()
    at /home/user/ws/src/mobile_interface/idl/MessengerTypeSupportImpl.cpp:1162
#28 0x0000555555d6bfc8 in OpenDDS::DCPS::(anonymous namespace)::opendds_idl_generated_messengertypesupportimpl_cpp_apfngh_get_minimal_type_map_private0 ()
    at /home/user/ws/src/mobile_interface/idl/MessengerTypeSupportImpl.cpp:1171
#29 0x0000555555d6c1c9 in OpenDDS::DCPS::opendds_idl_generated_messengertypesupportimpl_cpp_apfngh_get_minimal_type_map0 ()
    at /home/user/ws/src/mobile_interface/idl/MessengerTypeSupportImpl.cpp:1182
#30 0x0000555555d69464 in OpenDDS::DCPS::getMinimalTypeMap<OpenDDS::DCPS::Messenger_Message_xtag> () at /home/user/ws/src/mobile_interface/idl/MessengerTypeSupportImpl.cpp:64
#31 0x0000555555d6b24d in Messenger::MessageTypeSupportImpl::getMinimalTypeMap (this=0x5555560a98f0) at /home/user/ws/src/mobile_interface/idl/MessengerTypeSupportImpl.cpp:625
#32 0x00007ffff60dbfa2 in OpenDDS::DCPS::TypeSupportImpl::to_type_info (this=0x5555560a98f8, type_info=...) at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/TypeSupportImpl.cpp:105
#33 0x00007ffff5f56d5d in OpenDDS::DCPS::DataWriterImpl::enable (this=0x5555560aa700) at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/DataWriterImpl.cpp:1497
#34 0x00007ffff6024fdb in OpenDDS::DCPS::PublisherImpl::create_datawriter (this=0x5555560aa160, a_topic=0x5555560a9a50, qos=..., a_listener=0x0, mask=4294967295)
    at /home/user/Downloads/OpenDDS-3.30/dds/DCPS/PublisherImpl.cpp:182
#35 0x0000555555b0732d in main (argc=1, argv=0x7fffffffd308) at /home/user/ws/src/mobile_interface/src/main.cpp:143
```
> Note: other crashes not report "../sysdeps/unix/sysv/linux/raise.c: No such file or directory." They crash in a free or in a if (!active_)

**Comment by vidalperezbohoyo** [comment]
It is a very veeery strange error, but the thing that fixed this is clean /devel /build and /install and recompile without debug. So simple that i have not tried. Knowing this, probably is a catkin error instead of OpenDDS,
